# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The Average Dev
tagline:          ""
description:      > #
  Hi, I'm Mark Chavez. I run my own web-based calendar and that's fine. Ideas are just ideas until you
  execute them. I like making applications that is of high-quality and valuable. Enjoy reading!


url:              https://github.com/mrkjlchvz
baseurl:          /

author:
  name:           "Mark Chavez"
  url:            https://github.com/mrkjlchvz

paginate:         5

# Custom vars
version:          2.1.0

twitter: https://twitter.com/mrkjlchvz
github:  https://github.com/mrkjlchvz
