# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The Dev Standard
tagline:          ""

url:              https://github.com/mrkjlchvz
baseurl:          http://markjoelchavez.com/

author:
  name:           "Mark Chavez"
  url:            https://github.com/mrkjlchvz

paginate:         5

gems: ["jekyll-seo-tag"]

# Custom vars
version:          2.1.0

email:   markchav3z@gmail.com
cv:      https://standardresume.co/markchavez
github:  https://github.com/mrkjlchvz
