# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Value Driven Software
description:      A blog focusing on Ruby and Elixir development.
tagline:          ""

url:              http://markjoelchavez.com
baseurl:          http://markjoelchavez.com/

author:
  name:           "Mark Chavez"
  url:            https://github.com/mrkjlchvz

paginate:         10

gems: ["jekyll-seo-tag"]

# Custom vars
version:          2.1.0

email:   markchav3z@gmail.com
github:  https://github.com/mrkjlchvz

twitter:
  username: mrkjlchvz
