# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The Average Dev
tagline:          ""
description:      > #
  Hi, I'm Mark Chavez. I write Ruby and started dabbling with Elixir. I like making applications that is of
  high-quality and valuable. Enjoy reading!


url:              https://github.com/mrkjlchvz
baseurl:          /

author:
  name:           "Mark Chavez"
  url:            https://github.com/mrkjlchvz

paginate:         5

# Custom vars
version:          2.1.0

email:   markchav3z@gmail.com
cv:      https://standardresume.co/markchavez
twitter: https://twitter.com/mrkjlchvz
github:  https://github.com/mrkjlchvz
